export const TOOLBOX = [
  {
    category: 'HR Tools',
    items: [
      { name: 'BambooHR', url: 'https://www.bamboohr.com' },
      { name: 'Gusto', url: 'https://gusto.com' },
      { name: 'Zoho People', url: 'https://www.zoho.com/people' },
      { name: 'Workable', url: 'https://www.workable.com' },
      { name: 'Greenhouse', url: 'https://www.greenhouse.io' },
      { name: 'LinkedIn Talent Hub', url: 'https://www.linkedin.com/talent-solutions' },
      { name: 'TalentLMS', url: 'https://www.talentlms.com' },
      { name: 'Coursera for Business', url: 'https://www.coursera.org/business' },
      { name: 'Lessonly', url: 'https://www.lessonly.com' },
      { name: 'ADP', url: 'https://www.adp.com' },
      { name: 'Rippling', url: 'https://www.rippling.com' },
      { name: 'Paychex', url: 'https://www.paychex.com' },
      { name: 'CultureAmp', url: 'https://www.cultureamp.com' },
      { name: 'Officevibe', url: 'https://officevibe.com' },
    ],
  },
  {
    category: 'IT & Tech Tools',
    items: [
      { name: 'Jira Service Management', url: 'https://www.atlassian.com/software/jira/service-management' },
      { name: 'Zendesk', url: 'https://www.zendesk.com' },
      { name: 'Freshservice', url: 'https://freshservice.com' },
      { name: 'Datadog', url: 'https://www.datadoghq.com' },
      { name: 'New Relic', url: 'https://newrelic.com' },
      { name: 'Sentry', url: 'https://sentry.io' },
      { name: '1Password Teams', url: 'https://1password.com/business' },
      { name: 'Okta', url: 'https://www.okta.com' },
      { name: 'Cloudflare Zero Trust', url: 'https://www.cloudflare.com/teams' },
      { name: 'GitHub', url: 'https://github.com' },
      { name: 'GitLab', url: 'https://gitlab.com' },
      { name: 'Visual Studio Code', url: 'https://code.visualstudio.com' },
      { name: 'Docker', url: 'https://www.docker.com' },
      { name: 'Zapier', url: 'https://zapier.com' },
      { name: 'Make (Integromat)', url: 'https://www.make.com' },
      { name: 'n8n', url: 'https://n8n.io' },
    ],
  },
  {
    category: 'Finance & Accounting',
    items: [
      { name: 'QuickBooks', url: 'https://quickbooks.intuit.com' },
      { name: 'Xero', url: 'https://www.xero.com' },
      { name: 'FreshBooks', url: 'https://www.freshbooks.com' },
      { name: 'Anaplan', url: 'https://www.anaplan.com' },
      { name: 'Float', url: 'https://float.com' },
      { name: 'Mosaic', url: 'https://www.mosaic.co' },
      { name: 'Expensify', url: 'https://www.expensify.com' },
      { name: 'Concur', url: 'https://www.concur.com' },
      { name: 'Ramp', url: 'https://ramp.com' },
      { name: 'Stripe', url: 'https://stripe.com' },
      { name: 'Square', url: 'https://squareup.com' },
      { name: 'Chargebee', url: 'https://www.chargebee.com' },
    ],
  },
  {
    category: 'Operations & Admin',
    items: [
      { name: 'Asana', url: 'https://asana.com' },
      { name: 'ClickUp', url: 'https://clickup.com' },
      { name: 'Monday.com', url: 'https://monday.com' },
      { name: 'When I Work', url: 'https://wheniwork.com' },
      { name: 'Deputy', url: 'https://www.deputy.com' },
      { name: 'DocuSign', url: 'https://www.docusign.com' },
      { name: 'PandaDoc', url: 'https://www.pandadoc.com' },
      { name: 'Adobe Sign', url: 'https://acrobat.adobe.com/us/en/sign.html' },
      { name: 'Sortly', url: 'https://www.sortly.com' },
      { name: 'AssetTiger', url: 'https://www.myassettag.com' },
      { name: 'Zoho Inventory', url: 'https://www.zoho.com/inventory' },
    ],
  },
  {
    category: 'Sales & Marketing',
    items: [
      { name: 'HubSpot', url: 'https://www.hubspot.com' },
      { name: 'Salesforce', url: 'https://www.salesforce.com' },
      { name: 'Pipedrive', url: 'https://www.pipedrive.com' },
      { name: 'Mailchimp', url: 'https://mailchimp.com' },
      { name: 'Sendinblue', url: 'https://www.sendinblue.com' },
      { name: 'ConvertKit', url: 'https://convertkit.com' },
      { name: 'Hootsuite', url: 'https://hootsuite.com' },
      { name: 'Buffer', url: 'https://buffer.com' },
      { name: 'Sprout Social', url: 'https://sproutsocial.com' },
      { name: 'Intercom', url: 'https://www.intercom.com' },
      { name: 'LiveChat', url: 'https://www.livechat.com' },
      { name: 'Drift', url: 'https://www.drift.com' },
    ],
  },
  {
    category: 'General Productivity & AI',
    items: [
      { name: 'Notion', url: 'https://www.notion.so' },
      { name: 'Confluence', url: 'https://www.atlassian.com/software/confluence' },
      { name: 'Google Workspace', url: 'https://workspace.google.com' },
      { name: 'Slack', url: 'https://slack.com' },
      { name: 'Microsoft Teams', url: 'https://www.microsoft.com/microsoft-teams' },
      { name: 'Discord', url: 'https://discord.com' },
      { name: 'Google Drive', url: 'https://drive.google.com' },
      { name: 'Dropbox', url: 'https://www.dropbox.com' },
      { name: 'OneDrive', url: 'https://onedrive.live.com' },
      { name: 'SmallPDF', url: 'https://www.smallpdf.com' },
      { name: 'iLovePDF', url: 'https://www.ilovepdf.com' },
      { name: 'Adobe Acrobat', url: 'https://acrobat.adobe.com' },
      { name: 'ChatGPT', url: 'https://chat.openai.com' },
      { name: 'Perplexity', url: 'https://www.perplexity.ai' },
      { name: 'Jasper AI', url: 'https://www.jasper.ai' },
    ],
  },
]

export default TOOLBOX
